#ColorScheme
[[plugins]]
repo = 'altercation/vim-colors-solarized'
#unite
[[plugins]]
repo = 'Shougo/unite.vim'
#unite用
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'
#File exproler
[[plugins]]
repo = 'cocopon/vaffle.vim'
#easy motion
[[plugins]]
repo = 'easymotion/vim-easymotion'
#分割画面リサイズ
[[plugins]]
repo = 'simeji/winresizer'
#ctags自動生成
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
#git操作
[[plugins]]
repo = 'tpope/vim-fugitive'
